baseURL = 'https://example.org/'
locale = 'it-it'
title = 'Federico'
theme = "congo"
copyright = "© 2026 Federico D'Ambrosio · Licenza [CC BY-ND 4.0](https://creativecommons.org/licenses/by-nd/4.0/)"


[params]
colorScheme = "navy"          # or pick another built-in scheme
defaultAppearance = "light"   # or "light" — sets initial mode before user toggles
autoSwitchAppearance = true   # respects OS prefers-color-scheme too
mainSections = ["posts"]
list.showSummary = true       # Show explicit summary of posts 
defaultContentLanguage = "it"

[params.homepage]
layout = "profile"          # Valid options are "page", "profile", or "custom"
showRecent = true           # Set to true to show your recent posts
recentLimit = 5             # Number of posts to display on the homepage
showMoreLink = true         # Shows a link to view all posts
showMoreLinkDest = "/posts" # Path to your full posts page


[params.author]
name = "Federico"
image = "img/blue_circle.png" # put file in /assets/img/
headline = "Il posto dove scrivo quello che scrivo. Il perché lo spiego **[qua](/posts/first-post.md)**."
links = [
    { twitter = "https://twitter.com/fededambri" },
    { rss = "/index.xml" },
    { email = "mailto:blog@dambrosio.nl" },
]
